config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag', to: 'store#index', as: :tag
  devise_for :users
  resources :carts
  resources :line_items
  resources :products
  resources :orders 
  resources :users, only: [:index, :edit, :update] do
    collection do
      get 'orders'
    end
  end
  root 'store#index', as: 'store_index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :assign_default_role

  validate :must_have_a_role, on: :update

  private 

  def must_have_a_role
    unless roles.any?
      errors.add(:roles, 'must have at least 1 role')
    end
  end

  def assign_default_role
    self.add_role(:customer) if self.roles.blank?
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[edit update]

  def index
    authorize! :index, User
    @users = User.all
  end

  def edit
    authorize! :update, @user
  end

  def update
    authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def orders
    authorize! :read, @user
    @user = current_user
    @orders = @user.orders
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(role_ids: [])
  end
end

app/views/users/edit.html.slim
div class="container"
  = form_with(model: @user) do |form|
    = form.collection_check_boxes :role_ids, Role.all, :id, :name
    = @user.errors[(:roles)]
    = form.submit

app/views/users/index.html.slim
div class="container"
  table class="table"
    thead
      tr
        th scope="col" #
        th scope="col" First name
        th scope="col" Last name
        th scope="col" Email
        th scope="col" Phone
        th scope="col" Role
        th scope="col" Action
    tbody
      - @users.each do |user|
        tr
          th scope="row" = user.id
          th  = user.first_name
          th  = user.last_name
          th  = user.email
          th  = user.phone
          th  = user.roles.pluck(:name)
          th  = link_to 'Edit', edit_user_path(user)

app/views/users/orders.html.slim
div class="container"
  table class="table"
    thead
      tr
        th scope="col" Order number
        th scope="col" Created at
        th scope="col" Price
        th scope="col" Action
    tbody
      - @orders.each do |order|
        tr
          td = order.id
          td = order.created_at.strftime("%m/%d/%Y %H:%M")
          td = order.total_price
          td = link_to "Подробнее", order_path(order)