config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag', to: 'store#index', as: :tag
  devise_for :users
  resources :carts
  resources :line_items
  resources :products
  resources :orders 
  resources :users, only: [:index, :edit, :update] do
    collection do
      get 'orders'
    end
  end
  root 'store#index', as: 'store_index'
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Expand at md</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <% if (current_user && (current_user.has_role? :admin)) || (current_user && (current_user.has_role? :manager))%>
            <li class="nav-item">
              <%= link_to 'Orders', orders_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Products', products_path, class: "nav-link" %>
            </li>
          <% end %>
          <% if current_user && (current_user.has_role? :admin) %>
            <li class="nav-item">
              <%= link_to 'Users', users_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown04">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
        <% if session[:cart_id] != nil %>
          <%= link_to cart_path(id: session[:cart_id]) do %>
          <div class="position-relative mx-1">
            <%= image_tag('index.jpeg', size: 40) %>
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary"><%= @cart.line_items.count %> <span class="visually-hidden">unread messages</span></span>
          </div>
        <% end %>
        <% end %>
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.email %></a>
            <ul class="dropdown-menu" aria-labelledby="dropdown04">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li>
                <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "Orders",  orders_users_path, class: "dropdown-item" %>
              </li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <%= button_to "Log_out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
        <% else %>
          <%= link_to "Sign_up",  new_user_registration_path , class: "btn btn-primary mr-1" %>
          <%= link_to "Sign_in", new_user_session_path, class: "btn btn-primary mx-1" %>
        <% end %>
        <!--<form>
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form> -->
      </div>
    </div>
  </nav>