config/routes.rb
Rails.application.routes.draw do
  get 'tags/:tag', to: 'store#index', as: :tag
  devise_for :users
  resources :carts
  resources :line_items
  resources :products
  resources :orders 
  resources :users, only: [:index, :edit, :update] do
    collection do
      get 'orders'
    end
  end
  root 'store#index', as: 'store_index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
        current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :set_cart, only: %i[show destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def show; end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html do
        redirect_to store_index_url,
                    notice: 'Your cart is currently empty'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_index_url, notice: 'Invalid cart'
  end
end

app/views/carts/_cart.html.slim
- unless cart.line_items.empty?
    article
        - if notice
            aside id="notice" = notice
        h2 Your Cart
        table class="table"
            thead
                tr
                    th scope="col" Quantity
                    th scope="col" Prodcut
                    th scope="col" Price
            = render(cart.line_items)
            tfoot
                tr
                    th colspan="2" Total:
                    td class="price" = number_to_currency(cart.total_price)
        div class="actions"
            div class="d-grid gap-2 d-md-block"
                = button_to 'Empty cart', cart, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary", style: "display: inline"
                = button_to 'Checkout', new_order_path, method: :get, class: "btn btn-danger", style: "display: inline"
        /* = button_to 'Checkout', new_order_path, method: :get, class: "checkout"%>
- else
	h3 Cart is empty. 
	= link_to 'Return to shop', store_index_path

app/views/carts/show.html.slim
div class="container"
  = render @cart